class CoursesBeforeLoginLocators:
    courses_link_locator = '/html/body/header/nav/div/div/div[2]/div[1]/ul/li[1]/a'
    login_link_locator = '//*[@id="accountGroup"]/ul/li[1]/a'
    signup_link_locator = '//*[@id="accountGroup"]/ul/li[2]/a'
    search_bar_locator = '//*[@id="users"]/div[2]/div/div[4]/input'
    course_library_link_locator = '//*[@id="home-tab"]'
    combo_link_locator = '//*[@id="offersList"]'
    free_library_link_locator = '//*[@id="contact-tab"]'
    codekata_link_locator = '//*[@id="sidebar"]/ul[1]/li[2]/a'
    webkata_link_locator = '//*[@id="sidebar"]/ul[1]/li[3]/a'
    debugging_link_locator = '//*[@id="debuggingset"]'
    ide_link_locator = '//*[@id="sidebar"]/ul[1]/li[5]/a'
    leaderboard_link_locator = '//*[@id="sidebar"]/ul[1]/li[6]/a'
    rewards_link_locator = '//*[@id="sidebar"]/ul[1]/li[7]/a'
    referral_link_locator = '//*[@id="sidebar"]/ul[1]/li[8]/a'