class SignUpPageLocators:
    logo_locator = '//*[@id="sign-in-page"]/div[2]/div/div/div[2]/div[1]/a/picture/img'
    google_button_locator = 'google-button'
    firstname_locator = 'firstName'
    lastname_locator = 'lastName'
    email_locator = 'emailInput'
    password_locator = 'passwordInput'
    mobile_locator = 'mobileNumberInput'
    signup_button_locator = 'signup'
    invalid_feedback_locator = 'invalid-feedback'